// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminAdmin: typeof import('./../pages/admin/Admin.vue')['default']
    AdminFile: typeof import('./../pages/admin/File.vue')['default']
    AdminHome: typeof import('./../pages/admin/Home.vue')['default']
    AdminPublish: typeof import('./../pages/admin/Publish.vue')['default']
    AdminSort: typeof import('./../pages/admin/Sort.vue')['default']
    AdminTag: typeof import('./../pages/admin/Tag.vue')['default']
    CollapseTransition: typeof import('./../components/CollapseTransition.vue')['default']
    LoginLogin: typeof import('./../pages/login/Login.vue')['default']
    Navigate: typeof import('./../pages/Navigate.vue')['default']
    PageFooter: typeof import('./../components/PageFooter.vue')['default']
    PageHeader: typeof import('./../components/PageHeader.vue')['default']
    ShowEdit: typeof import('./../components/ShowEdit.vue')['default']
    SortSelect: typeof import('./../components/SortSelect.vue')['default']
    TagSelect: typeof import('./../components/TagSelect.vue')['default']
    UserAvatar: typeof import('./../components/UserAvatar.vue')['default']
    YHandle: typeof import('./../components/YHandle.vue')['default']
  }
}

export { }
