// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminAdmin: typeof import('./../pages/admin/Admin.vue')['default']
    AdminFile: typeof import('./../pages/admin/File.vue')['default']
    AdminHome: typeof import('./../pages/admin/Home.vue')['default']
    AdminPublish: typeof import('./../pages/admin/Publish.vue')['default']
    AdminSort: typeof import('./../pages/admin/Sort.vue')['default']
    AdminTag: typeof import('./../pages/admin/Tag.vue')['default']
    CollapseTransition: typeof import('./../components/CollapseTransition.vue')['default']
    LoginLogin: typeof import('./../pages/login/Login.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    Navigate: typeof import('./../pages/Navigate.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    PageFooter: typeof import('./../components/PageFooter.vue')['default']
    PageHeader: typeof import('./../components/PageHeader.vue')['default']
    ShowEdit: typeof import('./../components/ShowEdit.vue')['default']
    SortSelect: typeof import('./../components/SortSelect.vue')['default']
    TagSelect: typeof import('./../components/TagSelect.vue')['default']
    UserAvatar: typeof import('./../components/UserAvatar.vue')['default']
    YHandle: typeof import('./../components/YHandle.vue')['default']
  }
}

export { }
